### ISSUE TITLE
Null values treated as strings

### ISSUE THREAD

**Issue by drakar** [DataResponsibly/DataSynthesizer#1]
Hi, 

In a float or int field, it appears that the pandas lib treats them as string fields rather than flat with null value.

Is there anyway to force float, either in the UI or in the pandas read method?

**Comment by haoyueping** [comment]
Hi drakar,

When missing values are spaces, pandas regards the whole column as strings, which might be the reason for this data type error.

The DataDescriber is just updated to skip the initial spaces when reading values from the cells of input CSV file. Please try and let me know if it works.

**Comment by drakar** [comment]
It still is not working. Here is what I do:
```python
>>> import pandas as pd
>>> df = pd.read_csv("file.csv")
>>> type(df['latitude'][1])
<class` 'str'>
>>>
```

In the .CSV file the fields are literally '<null>' which is a string, but can it be treated as a null value or coerced into a float?

**Comment by stoyanovich** [comment]
Haoyue,

Please look into this.

Julia.

On 8/30/17 1:33 PM, Aaron Drake wrote:

It still is not working. Here is what I do:

>>> import pandas as pd
>>> df = pd.read_csv("file.csv")
>>> type(df['latitude'][1])
<class` 'str'>
>>>

In the .CSV file the fields are literally '' which is a string, but can it be treated as a null value or coerced into a float?

**Comment by haoyueping** [comment]
Pandas allows user-defined NULL values when reading CSV file by parameter `na_values`. See [`pandas.read_csv`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).

DataSynthesizer supports this functionality now, which is essentially by adding parameter `null_values` and passing it to `pandas.read_csv` in `DataDescriber. read_dataset_from_csv`.

In your case, you can try `df = pd.read_csv("file.csv", na_values="'<null>'")`.

**Comment by drakar** [comment]
@haoyueping Thank you very much!

**Comment by haoyueping** [comment]
@drakar No problem. Thanks for your feedback!
