### ISSUE TITLE
Can't run webui - 502 gateway error

### ISSUE THREAD

**Issue by oregonpillow** [DataResponsibly/DataSynthesizer#19]
When i run the webui i get an error. 

This is what i did:

```
PYTHONPATH=../DataSynthesizer python manage.py runserver     
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
```
Then i go to `http://127.0.0.1:8000/` and go to tools->Data Synthesizer tool
and i get a Gateway 502 error'?

I figured trying again annd running `python manage.py migrate` would fix the issue but instead i get `ModuleNotFoundError: No module named 'DataGenerator'`...

I followed the installation instructions as described in readme.

**Comment by haoyueping** [comment]
Hi, please try `http://127.0.0.1:8000/synthesizer/` after running the local server.
