### ISSUE TITLE
Different modes

### ISSUE THREAD

**Issue by patwater** [DataResponsibly/DataSynthesizer#2]
Apologies if I'm just being dense though is there documentation on the different modes enabled by DataSynthesizer? Aka random, independent attribute, correlated. Guessing has to do with assumptions with the data generating process for the dataset in question though would love to dive deeper.

PS love the goals with this tool!

**Comment by haoyueping** [comment]
Thanks! I'm glad to have your feedback. You can find a paper (cr-datasynthesizer-privacy.pdf) in root directory of this repo, which explains the three modes. Please let me know if you have any questions.
