### ISSUE TITLE
Django errors when uploading data

### ISSUE THREAD

**Issue by oregonpillow** [DataResponsibly/DataSynthesizer#22]
On the DataSynthesizer landing page when you click on upload data it always gives me this error, regardless of whether I select a demo file or upload my own data. Any suggestions?? : 

<img width="1280" alt="Screenshot 2020-05-20 at 18 56 18" src="https://user-images.githubusercontent.com/53374403/82474830-e8067f80-9acb-11ea-9492-b364f30840b0.png">

**Comment by oregonpillow** [comment]
fixed with:
`PYTHONPATH=../DataSynthesizer python manage.py migrate`

**Comment by Thuener** [comment]
I also had this issue. I think the best thing is to change the README.md:
```
# install django
pip install django

# go to the directory for webUI
git clone https://github.com/DataResponsibly/DataSynthesizer.git
cd DataSynthesizer/webUI/

# run the server
python manage.py migrate
python manage.py runserver
```

If the team wants I can create a pull request with that.
