### ISSUE TITLE
Pip Install Problems

### ISSUE THREAD

**Issue by GuidoPinaresCh** [DataResponsibly/DataSynthesizer#27]
* DataSynthesizer version: 
* Python version: 3.7.9
* Operating System: Windows 10

### Description

Im trying to install DataSynthesizer on Anaconda for using on jupiter notebook

### What I Did

```
When i pip install DataSynthesizer i get this error:

ERROR: Could not find a version that satisfies the requirement DataSynthesizer (from versions: none)
ERROR: No matching distribution found for DataSynthesizer

I also try with conda install DataSynthesizer and get the next message

PackagesNotFoundError: The following packages are not available from current channels:

  - datasynthesizer


```

**Comment by haoyueping** [comment]
It is probably due to the requirement of Python version. You may create a new environment `conda create -n myenv python=3.8`, and test if DataSynthesizer can be installed properly.
