### ISSUE TITLE
Django data upload

### ISSUE THREAD

**Issue by patwater** [DataResponsibly/DataSynthesizer#3]
When I try to upload <any> dataset to the Django app I get the following error:

[ParserError at _synthesizer_proc_data_dash_.pdf](https://github.com/DataResponsibly/DataSynthesizer/files/1489572/ParserError.at._synthesizer_proc_data_dash_.pdf)

**Comment by haoyueping** [comment]
The exception raised when reading CSV and decoding Byte 0xa8. Can you share with me your input dataset?
