### ISSUE TITLE
Speeding up DataSynthesizer

### ISSUE THREAD

**Issue by mahmoudibrahim98** [DataResponsibly/DataSynthesizer#30]
* DataSynthesizer version:
* Python version:
* Operating System:

### Description
Hello, 
I'm trying to synthesizer  datasets with high number of attributes (above 50). However, the data synthesis process is taking too long (multiple hours). 
Is there a way we can speed up the process? Can we run it on the GPU?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by haoyueping** [comment]
Hi, are you familiar with GPU acceleration for Python? If so, it would be great if you can help adapting the code to GPU. I will be glad to collaborate.

I have little expertise in this topic. It seems that Numba is the go-to solution, but the operations accelerated by Numba seem to be limited. At least a simple `@jit` decorator does not work for DataSynthesizer.

What do you think?

**Comment by mahmoudibrahim98** [comment]
Hello, unfortunately I have no experience with GPU acceleration.
