### ISSUE TITLE
The tool fails to reproduce any kind of data

### ISSUE THREAD

**Issue by federicogibertoni** [DataResponsibly/DataSynthesizer#35]
* DataSynthesizer version: 0.19
* Python version: 3.7.3
* Operating System: GNU/Linux Debian 10

Hi,

I have a really small clinical dataset with 176 rows and 80 columns. Some of the variables are considered to be categorical and other continuous; all the NaNs have been replaced with -1 in integer/float and "" in string.

I filled the configuration dictionaries attr_to_datatype, categorical_attributes and candidate_keys with the variables in my dataset.
I'm trying to reproduce the example notebook in correlated attribute mode (I know for sure there are some correlations in my dataset) without touching anything else except for the settings mentioned above.

It seems like nothing is working properly because none of the data generated follows the real distribution of the original dataset but it looks like they're following some sort of uniform distribution. Here you can see some examples:

![issue_example_1](https://user-images.githubusercontent.com/32088903/129350592-7e85f673-6830-4a36-80e9-baff98258e84.png)

![issue_example_2](https://user-images.githubusercontent.com/32088903/129350603-7ae70a2e-2262-451d-b0b3-7f47b217a020.png)

I can't find any solution to my problem and I've been trying every kind of settings combination but none seems to work correctly.
Maybe I'm missing something or there might be some problem in the generation process.

What do you suggest to do ? Thank you.

**Comment by haoyueping** [comment]
Hi, it may be caused by the injection of too much noise. Please try increasing the `epsilon`, e.g. `epsilon=10` and `epsilon=100`, and see if the correlations are reconstructed.

**Comment by federicogibertoni** [comment]
Hi, thank you for your reply.

I don't know why but it looks like that increasing ```epsilon``` as you suggest worsen the situation.
I tried to turn off differential privacy setting ```epsilon=0``` and now the tool is able to reproduce the distributions of all attributes; but I needed a certain level of privacy so I can't turn it off.

How can I solve this problem ?

**Comment by haoyueping** [comment]
Hi, it is unexpected that increasing `epsilon` makes the output more random/noisy/uniform. If you can provide me a minimal reproducible example using synthetic non-sensitive data, I can look into it and see if I can find the bug.

**Comment by federicogibertoni** [comment]
Hi, unluckily I'm unable to give you some the data as they're no more available even for me. But, the problem lasted during all this time and I was able to solve it only by setting `epsilon=0`.
