### ISSUE TITLE
DateTime issues

### ISSUE THREAD

**Issue by artemgur** [DataResponsibly/DataSynthesizer#37]
* DataSynthesizer version: 0.1.10
* Python version: 3.7.13
* Operating System: Ubuntu 18.04.5 LTS

I use Google Colab.

### Description

My input dataset has a column, which contains 2 distinct DateTime values: "2020-09-14", "2020-09-16".

describe_dataset_in_correlated_attribute_mode works correctly.

But when I run generate_dataset_in_correlated_attribute_mode, following error appears (I also included full traceback):
> ValueError: invalid literal for int() with base 10: '2020-09-14'

I did some investigation, and the relevant part of description file looks like this (I also included full description file):

"dateTime": {
    "name": "dateTime",
    "data_type": "DateTime",
    "is_categorical": true,
    "is_candidate_key": false,
    "min": 1600041600.0,
    "max": 1600214400.0,
    "missing_rate": 0.0,
    "distribution_bins": [
        "2020-09-14",
        "2020-09-16"
    ],
    "distribution_probabilities": [
        0.6587202007528231,
        0.341279
    ]
},

For some reason, "min" and "max" are timestamps, and "distribution_bins" are strings. It's suspicious.

It's the only place in the description flie where the datetime literals "2020-09-14" and "2020-09-16" appear.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-17-4621f1d6556b>](https://localhost:8080/#) in <module>()
      1 generator = DataGenerator()
----> 2 generator.generate_dataset_in_correlated_attribute_mode(num_tuples_to_generate, description_file)
      3 generator.save_synthetic_data(synthetic_data)

9 frames
[/usr/local/lib/python3.7/dist-packages/DataSynthesizer/DataGenerator.py](https://localhost:8080/#) in generate_dataset_in_correlated_attribute_mode(self, n, description_file, seed)
     68 
     69             if attr in self.encoded_dataset:
---> 70                 self.synthetic_dataset[attr] = column.sample_values_from_binning_indices(self.encoded_dataset[attr])
     71             elif attr in candidate_keys:
     72                 self.synthetic_dataset[attr] = column.generate_values_as_candidate_key(n)

[/usr/local/lib/python3.7/dist-packages/DataSynthesizer/datatypes/DateTimeAttribute.py](https://localhost:8080/#) in sample_values_from_binning_indices(self, binning_indices)
     83     def sample_values_from_binning_indices(self, binning_indices):
     84         column = super().sample_values_from_binning_indices(binning_indices)
---> 85         column[~column.isnull()] = column[~column.isnull()].astype(int)
     86         return column

[/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in astype(self, dtype, copy, errors)
   5813         else:
   5814             # else, only a single dtype is given
-> 5815             new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
   5816             return self._constructor(new_data).__finalize__(self, method="astype")
   5817 

[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py](https://localhost:8080/#) in astype(self, dtype, copy, errors)
    416 
    417     def astype(self: T, dtype, copy: bool = False, errors: str = "raise") -> T:
--> 418         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    419 
    420     def convert(

[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py](https://localhost:8080/#) in apply(self, f, align_keys, ignore_failures, **kwargs)
    325                     applied = b.apply(f, **kwargs)
    326                 else:
--> 327                     applied = getattr(b, f)(**kwargs)
    328             except (TypeError, NotImplementedError):
    329                 if not ignore_failures:

[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/blocks.py](https://localhost:8080/#) in astype(self, dtype, copy, errors)
    589         values = self.values
    590 
--> 591         new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
    592 
    593         new_values = maybe_coerce_values(new_values)

[/usr/local/lib/python3.7/dist-packages/pandas/core/dtypes/cast.py](https://localhost:8080/#) in astype_array_safe(values, dtype, copy, errors)
   1307 
   1308     try:
-> 1309         new_values = astype_array(values, dtype, copy=copy)
   1310     except (ValueError, TypeError):
   1311         # e.g. astype_nansafe can fail on object-dtype of strings

[/usr/local/lib/python3.7/dist-packages/pandas/core/dtypes/cast.py](https://localhost:8080/#) in astype_array(values, dtype, copy)
   1255 
   1256     else:
-> 1257         values = astype_nansafe(values, dtype, copy=copy)
   1258 
   1259     # in pandas we don't store numpy str dtypes, so convert to object

[/usr/local/lib/python3.7/dist-packages/pandas/core/dtypes/cast.py](https://localhost:8080/#) in astype_nansafe(arr, dtype, copy, skipna)
   1172         # work around NumPy brokenness, #1987
   1173         if np.issubdtype(dtype.type, np.integer):
-> 1174             return lib.astype_intsafe(arr, dtype)
   1175 
   1176         # if we have a datetime/timedelta array of objects

/usr/local/lib/python3.7/dist-packages/pandas/_libs/lib.pyx in pandas._libs.lib.astype_intsafe()

ValueError: invalid literal for int() with base 10: '2020-09-14'

The code which I ran:
generator = DataGenerator()
generator.generate_dataset_in_correlated_attribute_mode(num_tuples_to_generate, description_file)
generator.save_synthetic_data(synthetic_data)

Description file:
[fns_fiscal_generated_description.zip](https://github.com/DataResponsibly/DataSynthesizer/files/8387721/fns_fiscal_generated_description.zip)

**Comment by haoyueping** [comment]
Thanks for reporting this error. It should be fixed in the latest version 0.1.11. Please check it out.

**Comment by artemgur** [comment]
Yes, now it works correctly.
