### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by PepijndeReus** [DataResponsibly/DataSynthesizer#41]
When I use the DataDescriber I get a file not found error. I would like to save the dataset description in a .json file that does not exist yet. I would like DataSynthesizer to create this file for me. Isn't there an option to add a small function that checks the filepath and then creates the empty file if the specified path/file is non-existent? Similar to these two lines of code on [this post](https://stackoverflow.com/a/34603829) from StackOverflow. Then I do not have to create empty files before running the programming.

I suggest adding these two lines in this function:
https://github.com/DataResponsibly/DataSynthesizer/blob/0bae2c18a3d6998e2f370fbf2fb816bebb8b0abc/DataSynthesizer/DataDescriber.py#L301-L303

Happy to hear your thoughts on this, thanks!

**Comment by haoyueping** [comment]
@PepijndeReus thanks for your suggestion! This featured has been added to DataSynthesizer 0.1.12

**Comment by PepijndeReus** [comment]
Issue resolved in [this commit](https://github.com/DataResponsibly/DataSynthesizer/commit/f9f469f6eb5e1f4cb0d97ebd733e4fd8a062e6e6)
