### ISSUE TITLE
correlated attribute mode example notebook throws errors

### ISSUE THREAD

**Issue by magic-lantern** [DataResponsibly/DataSynthesizer#6]
I've followed the installation instructions and am attempting to run "DataSynthesizer Usage (correlated attribute mode).ipynb" I get the following error when running Step 4:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-4621f1d6556b> in <module>()
      1 generator = DataGenerator()
----> 2 generator.generate_dataset_in_correlated_attribute_mode(num_tuples_to_generate, description_file)
      3 generator.save_synthetic_data(synthetic_data)

~/DataSynthesizer/DataSynthesizer/DataGenerator.py in generate_dataset_in_correlated_attribute_mode(self, n, description_file, seed)
     68 
     69             if attr in self.encoded_dataset:
---> 70                 self.synthetic_dataset[attr] = column.sample_values_from_binning_indices(self.encoded_dataset[attr])
     71             elif attr in candidate_keys:
     72                 self.synthetic_dataset[attr] = column.generate_values_as_candidate_key(n)

~/DataSynthesizer/DataSynthesizer/datatypes/IntegerAttribute.py in sample_values_from_binning_indices(self, binning_indices)
     18 
     19     def sample_values_from_binning_indices(self, binning_indices):
---> 20         column = super().sample_values_from_binning_indices(binning_indices)
     21         column[~column.isnull()] = column[~column.isnull()].astype(int)
     22         return column

~/DataSynthesizer/DataSynthesizer/datatypes/AbstractAttribute.py in sample_values_from_binning_indices(self, binning_indices)
     96     def sample_values_from_binning_indices(self, binning_indices):
     97         """ Convert binning indices into values in domain. Used by both independent and correlated attribute mode. """
---> 98         return  binning_indices.apply(lambda x: self.uniform_sampling_within_a_bin(x))
     99 
    100     def uniform_sampling_within_a_bin(self, binning_index):

~/anaconda3/lib/python3.6/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
   3190             else:
   3191                 values = self.astype(object).values
-> 3192                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   3193 
   3194         if len(mapped) and isinstance(mapped[0], Series):

pandas/_libs/src/inference.pyx in pandas._libs.lib.map_infer()

~/DataSynthesizer/DataSynthesizer/datatypes/AbstractAttribute.py in <lambda>(x)
     96     def sample_values_from_binning_indices(self, binning_indices):
     97         """ Convert binning indices into values in domain. Used by both independent and correlated attribute mode. """
---> 98         return  binning_indices.apply(lambda x: self.uniform_sampling_within_a_bin(x))
     99 
    100     def uniform_sampling_within_a_bin(self, binning_index):

~/DataSynthesizer/DataSynthesizer/datatypes/AbstractAttribute.py in uniform_sampling_within_a_bin(self, binning_index)
    106             bins = self.distribution_bins.copy()
    107             bins.append(2 * bins[-1] - bins[-2])
--> 108             return uniform(bins[binning_index], bins[binning_index + 1])

TypeError: list indices must be integers or slices, not float
```

The other notebooks work just fine, so it seems my environment is setup correctly, but there is a bug with the correlated attribute mode.

**Comment by haoyueping** [comment]
The TypeError is about indices not integers. These indices are from `self.encoded_dataset` in `DataGenerator.py`, which is supposed to be a DataFrame of integer values. Can you print `self.encoded_dataset` at line 68 in `DataGenerator.py` to see whether all its values are integer?

**Comment by magic-lantern** [comment]
This is what I get when printing self.encoded_dataset from DataGenerator.py. Looks like all the values except education are float values.

<pre>
DataGenerator.py - printing self.encoded_dataset
       education  income  relationship  marital-status  sex   age
0             15     2.0           1.0             4.0  2.0   6.0
1             16     2.0           2.0             4.0  1.0  10.0
2             15     2.0           3.0             4.0  0.0   6.0
3             15     0.0           3.0             4.0  1.0   6.0
4             11     2.0           0.0             7.0  1.0   1.0
5             15     0.0           3.0             4.0  2.0   3.0
6             11     0.0           2.0             7.0  2.0   2.0
7             16     2.0           6.0             2.0  0.0   2.0
8             16     0.0           6.0             2.0  1.0   7.0
9             11     0.0           6.0             2.0  2.0   4.0
10            16     2.0           4.0             4.0  0.0   2.0
11            14     1.0           0.0             2.0  1.0   4.0
12            15     2.0           1.0             4.0  1.0   4.0
13            16     2.0           0.0             2.0  1.0  10.0
14             5     0.0           4.0             4.0  0.0   1.0
15             7     0.0           6.0             2.0  1.0   5.0
16             1     0.0           4.0             7.0  0.0   3.0
17            16     0.0           6.0             2.0  2.0   9.0
18            16     1.0           0.0             2.0  2.0  20.0
19            16     2.0           6.0             2.0  2.0   8.0
20            16     0.0           1.0             7.0  2.0   5.0
21            16     2.0           6.0             2.0  1.0   9.0
22            11     2.0           0.0             2.0  1.0  13.0
23            16     2.0           0.0             2.0  1.0   8.0
24             8     2.0           0.0             2.0  2.0   6.0
25            15     2.0           4.0             4.0  2.0   1.0
26             9     0.0           0.0             7.0  1.0   2.0
27            16     0.0           3.0             4.0  0.0   1.0
28            14     2.0           1.0             7.0  2.0   3.0
29            11     0.0           6.0             2.0  1.0   5.0
...          ...     ...           ...             ...  ...   ...
32531          9     2.0           0.0             2.0  2.0   2.0
32532         11     1.0           0.0             2.0  1.0   7.0
32533         16     2.0           6.0             2.0  2.0   5.0
32534         11     0.0           1.0             7.0  2.0   3.0
32535         16     1.0           6.0             2.0  2.0  20.0
32536         16     2.0           3.0             7.0  0.0  11.0
32537         16     0.0           4.0             0.0  2.0   4.0
32538          7     2.0           6.0             4.0  0.0   2.0
32539         11     0.0           6.0             2.0  0.0   7.0
32540         16     2.0           6.0             2.0  0.0  10.0
32541         15     2.0           4.0             7.0  0.0   3.0
32542         16     0.0           6.0             2.0  2.0  14.0
32543         16     2.0           6.0             4.0  1.0   1.0
32544         10     1.0           0.0             2.0  2.0   3.0
32545         11     2.0           5.0             2.0  2.0  12.0
32546         16     2.0           6.0             4.0  2.0   0.0
32547         16     1.0           0.0             2.0  2.0   2.0
32548         16     0.0           1.0             4.0  1.0  20.0
32549          9     1.0           0.0             2.0  1.0   5.0
32550          9     0.0           6.0             2.0  0.0  20.0
32551         16     1.0           0.0             2.0  2.0  20.0
32552         16     0.0           3.0             4.0  0.0   2.0
32553         11     2.0           4.0             7.0  0.0  10.0
32554         11     2.0           3.0             4.0  1.0   9.0
32555         16     0.0           6.0             4.0  2.0   2.0
32556         16     2.0           4.0             0.0  2.0   2.0
32557         15     0.0           6.0             7.0  1.0  11.0
32558         15     2.0           4.0             4.0  0.0  20.0
32559         11     2.0           4.0             7.0  2.0   0.0
32560         16     2.0           6.0             4.0  2.0   0.0

[32561 rows x 6 columns]
DataGenerator.py - end printing self.encoded_dataset
</pre>

It seems that there is a bug in the function generate_encoded_dataset - perhaps due to a change in Pandas or Numpy since the software was developed. One alternative would be to convert all columns to integers in `generate_dataset_in_correlated_attribute_mode()` like this:

```
self.encoded_dataset[self.encoded_dataset.columns] = self.encoded_dataset[self.encoded_dataset.columns].astype(int)
```

or modify `generate_encoded_dataset()` to ensure all values are integers instead of floats.

If the problem is as simple as just fixing self.encoded_dataset, then I'm happy to play around with this some more and submit a patch. 

Are you open to accepting pull requests from outside collaborators?

**Comment by haoyueping** [comment]
Yes, please feel free to submit a patch to fix this bug. Your solution looks good. Thanks for your contribution!

**Comment by magic-lantern** [comment]
Fix has been merged.
